### ISSUE TITLE
Not all nodes on ladder diagram

### ISSUE THREAD

**Issue by denyspozniak** [sipcapture/hep-wireshark#12]
Hello!

Below is the config from Kamailio (it has Public and Private interfaces) and tcpdump parameters:

```loadmodule "siptrace.so"
modparam("siptrace", "duplicate_uri", "sip:127.0.0.1:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "trace_flag", 22)
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "hep_version",2)
```
If I use **sngrep**, it shows well.
`sngrep -d lo -L udp:127.0.0.1:9060 -c`

![Screenshot_1](https://user-images.githubusercontent.com/22612345/73854310-01e0c700-483b-11ea-8c6a-555d08906e60.png)

If I collect trace with **tcpdump**, Wireshark shows only two parties in the conversation (which packets came from).  
`tcpdump -i lo port 9060 -w /home/sngrep/hepv2.pcap`

![Screenshot_2](https://user-images.githubusercontent.com/22612345/73854366-1b820e80-483b-11ea-82f8-6d5940fbb8dd.png)

But in HEP packet payload IPs are present.

![Screenshot_3](https://user-images.githubusercontent.com/22612345/73854369-1d4bd200-483b-11ea-9024-a048413a2ab4.png)

PS. **I suspect that the problem is not related to your plugin, but maybe you know solution**

**Comment by lmangani** [comment]
I'm not sure I understand - what would be the expected result? The wireshark flow is for HEP and will only show source and destination of the HEP packets, nothing related to their contents.

**Comment by denyspozniak** [comment]
Yes, exactly. The question was about how to display SIP call-flow using IPs from HEP content.

**Comment by lmangani** [comment]
You cannot do so in wireshark, the plugin only provides for the encapsulation dissection and display, and does not attempt to have the SIP flow represented - HEP is an encapsulation protocol so the raw network flow contents are only related to the outer layers. If you know of any other Wireshark LUA plugin which provides that type of feature for an encapsulation protocol, please give us a pointer and we'll gladly take a look.

You can only display HEP flows in HOMER, HEPIC or SNGREP.
