### ISSUE TITLE
Cant' decode HEP2 protocol

### ISSUE THREAD

**Issue by rparadinha** [sipcapture/hep-wireshark#4]
Hi,
I installed the hep.lua plugin in Wireshark but I can't decode HEP2 packages:
I got this error:

![image](https://user-images.githubusercontent.com/17499767/28361886-3ceedc62-6c72-11e7-9d47-4404d7a430c7.png)

I'm using the Wireshark version 2.2.8 in OS X.

Thanks in advance,
Roberto

**Comment by giavac** [comment]
Hi @rparadinha - would you please provide an example pcap where that error happens?
So I'll try to reproduce and fix.
Thank you.

**Comment by rparadinha** [comment]
Hi @giavac,

Sorry the delay, following an example:
[HEPv2 protocol - can not decode.pcapng.zip](https://github.com/sipcapture/hep-wireshark/files/1446123/HEPv2.protocol.-.can.not.decode.pcapng.zip)

Thanks,
Roberto

**Comment by giavac** [comment]
Hi @rparadinha - this change should fix the issue. For some reason the protocol ID in your packets is `01`, which I hadn't covered.

**Comment by rparadinha** [comment]
It's works now:
![image](https://user-images.githubusercontent.com/17499767/32491425-8d5ae73e-c3ae-11e7-8e0c-2b5d1489adb8.png)
Thanks @giavac

**Comment by giavac** [comment]
Great, happy dissecting @rparadinha
