### ISSUE TITLE
infinite loop on parsing gzipped packet

### ISSUE THREAD

**Issue by mritalian** [sipcapture/hep-wireshark#5]
For chunk_type, 00000011, I suggest you handle it as a normal payload even if it shows jibberish, because right now it gets stuck in an infinite loop and hangs wireshark.

**Comment by giavac** [comment]
Hi @awiefhlwheajrliawuqfhlahfjsd - do you have a sample pcap we can use to try and reproduce the issue? Thanks.

**Comment by mritalian** [comment]
Sure here you go

[hep3_compressed.pcap.pcapng.zip](https://github.com/sipcapture/hep-wireshark/files/1230073/hep3_compressed.pcap.pcapng.zip)

**Comment by mritalian** [comment]
The fix is simply to process the data the same way you do for an uncompressed payload,  This won't render anything meaningful in wireshark but it fixes the infinite loop.

**Comment by giavac** [comment]
Thanks @awiefhlwheajrliawuqfhlahfjsd
